---
title: "Contributing"
output:
  bookdown::html_document2:
  #base_format: rmarkdown::html_vignette
  #highlight: tango
  number_sections: false
toc: true
toc_float: true
fig_caption: yes
link-citations: yes
bibliography: bib/biblio-jSDM.bib
biblio-style: bib/jae.bst
csl: bib/journal-of-applied-ecology.csl
pkgdown:
  as_is: true
vignette: >
 %\VignetteIndexEntry{Contributing}
 %\VignetteEncoding{UTF-8}
 %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---

# Community guidelines

The `jSDM` R package is Open Source and released under
the [GNU GPL version 3 license ](https://www.gnu.org/licenses/gpl-3.0.en.html). Anybody who is interested can contribute to the package development. 
There are many ways to contribute, such as writing tutorials, examples or tests, improving documentation, submitting bug reports and feature requests, or writing code to provide new functionalities which can be incorporated into future versions of the package. Every contributor must agree to follow the project's [Code Of Conduct](https://ecology.ghislainv.fr/jSDM/Code_of_conduct.html).

## Report an issue

If you want to report a bug, request a feature, or discuss an issue,
please open an [issue](https://github.com/ghislainv/jSDM/issues) on the GitHub
project page.

## Contribute to code

Changes to the source code and documentation should be made via GitHub
pull requests (PR).

You can learn how to do this from this *free* video series [How to Contribute to an Open Source Project on GitHub](https://egghead.io/courses/how-to-contribute-to-an-open-source-project-on-github),
Aaron Meurer's [tutorial on the git workflow](https://www.asmeurer.com/git-workflow/), or the guide [How to Contribute to Open Source](https://opensource.guide/how-to-contribute/).

The important steps to follow are:

1. Start by creating a fork of the `jSDM` repository
2. Make changes to the source code on a development branch, not the default *master* branch
3. Keep your fork's master and development branches up to date with changes in the ``jSDM`` repository
4. Commit the changes you made. Chris Beams has written a [guide](https://chris.beams.io/posts/git-commit/) on how to write good commit messages.
5. Push to your fork and submit a pull request.