---
title: "Application of jSDM on forest data from Madagascar"
output:
  bookdown::html_document2:
  #base_format: rmarkdown::html_vignette
  #highlight: tango
  number_sections: true
toc: true
toc_float: true
fig_caption: yes
link-citations: yes
bibliography: bib/biblio-jSDM.bib
biblio-style: bib/jae.bst
csl: bib/journal-of-applied-ecology.csl
pkgdown:
  as_is: true
vignette: >
 %\VignetteIndexEntry{Application of JSDM on forest data from Madagascar}
 %\VignetteEncoding{UTF-8}
 %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r data}
library(raster)
library(rgdal)
library(readr)
library(dplyr)

# forest inventory
trees <- read_csv("~/Documents/projet_BioSceneMada/Report/data/forest_inventory_Madagascar.csv")
trees <- trees[-which(is.na(trees$sp)),]
trees$plot <- as.character(trees$plot)
plots <- unique(trees$plot)
nplot <- length(plots)
sp <- unique(trees$taxize)
nsp <- length(sp)
# presence/absence of each species on each plot
nobs <- nplot*nsp
Y <- rep(0,nobs)
site <- rep(plots,nsp)
species <- rep(sp, each=nplot)
data <- data.frame(Y=Y, species=species, site=site)
for (n in 1:nrow(trees)){
 data$Y[which(data$site==trees$plot[n] & data$species==trees$taxize[n])] <- 1 
}

# climatic variables 
s <- stack("~/Code/Report/data/current.tif")
names(s) <- c(paste("tmin",1:12,sep=""),paste("tmax",1:12,sep=""),
              paste("prec",1:12,sep=""),paste("bio",1:19,sep=""),
              paste("pet",1:12,sep=""),"pet","cwd","ndm")
# get intersting covariables 
clim_var <- dropLayer(s, c(1:36,38,39,41:47,49,50,52:68,70))
names(clim_var) <- c("temp","prec","sais_temp","sais_prec","cwd")

# spatial points of each plot
longlat <- SpatialPoints(unique(cbind(trees$long,trees$lat)))
proj4string(longlat) <- CRS("+proj=longlat +ellps=clrk66")

# latlong to UTM38S projection 
xy <- spTransform(longlat, CRS("+init=epsg:32738"))

# extract climatic data on each plot
clim <-  raster::extract(clim_var,xy)
clim2 <- clim^2
colnames(clim2)<-paste(colnames(clim),rep("2",ncol(clim)),sep="")
pos = unique(trees[,c("long","lat","plot")])
colnames(pos) <- c("long","lat","site")

# Add squared data
data_clim2 <- cbind(clim,clim2,pos)
nparam <- ncol(data_clim2) -3
library(tidyverse)
# order plot
ord_data_clim2 <- data_clim2[sort(data_clim2$site, index.return=TRUE)$ix,]

# reduced centered data
scaled_data_clim2 <- as_tibble(cbind(scale(ord_data_clim2[1:nparam]),ord_data_clim2[(nparam+1):ncol(ord_data_clim2)]))

## Design matrix
X <- data.frame(intercept=rep(1,nplot),select(as_tibble(scaled_data_clim2),-lat,-long, -site))
np<-ncol(X)
write.csv(X, "~/Code/Report/data/X.csv", row.names = F)
```
