# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Rcpp_jSDM_binomial <- function(ngibbs, nthin, nburn, Y, T, X, beta_start, mubeta, Vbeta, seed, ropt, verbose) {
    .Call(`_jSDM_Rcpp_jSDM_binomial`, ngibbs, nthin, nburn, Y, T, X, beta_start, mubeta, Vbeta, seed, ropt, verbose)
}

Rcpp_jSDM_probit_block <- function(ngibbs, nthin, nburn, Y, T, X, param_start, Vparam, muparam, VW, W_start, alpha_start, Valpha_start, shape, rate, seed, verbose) {
    .Call(`_jSDM_Rcpp_jSDM_probit_block`, ngibbs, nthin, nburn, Y, T, X, param_start, Vparam, muparam, VW, W_start, alpha_start, Valpha_start, shape, rate, seed, verbose)
}

